# Generated by Django 4.2.7 on 2025-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='mime_type',
            field=models.CharField(blank=True, help_text='Type MIME du fichier', max_length=100, null=True),
        ),
    ]
