# Generated by Django 4.2.7 on 2025-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_alter_resource_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la ressource', null=True),
        ),
    ]
